### ISSUE TITLE
yapf error: "yapf: input filenames did not match any python files"

### ISSUE THREAD

**Issue by lld2001** [purcell/emacs-reformatter#39]
I use the following config to format python code:

```emacs-lisp
(reformatter-define yapf :program "yapf" :args '("-"))
```

[yapf](https://github.com/google/yapf) does not format caused by the error:
```txt
yapf: input filenames did not match any python files
```

**Comment by lld2001** [comment]
My env is "GNU Emacs 29.0.50 (build 1, x86_64-w64-mingw32) of 2022-07-01". 

I debug with the following:
```emacs-lisp
(apply 'call-process "yapf"
	   "d:/msys64/home/hh/test/hello.py"
       '((:file "c:/Users/hh/AppData/Local/Temp/yapfoKFr2b") "c:/Users/hh/AppData/Local/Temp/yapfPBnoV2")
       nil
       '("-"))
```

and add `print("argv",argv)` in yapf's `main()` function. The output of temp files are:
![Uploading image.png…]()

**Comment by purcell** [comment]
Looks like yapf does not support the `-`. Just leave off that argument: the [yapf README](https://github.com/google/yapf) says that if you pass it no filenames, it reads from stdin.

**Comment by lld2001** [comment]
I tested by removing `-` argument, the error still same.

and the following snippet also failed.

```emacs-lisp
(apply 'call-process "yapf"
	   "d:/msys64/home/hh/test/hello.py"
       '((:file "c:/Users/hh/AppData/Local/Temp/yapfoKFr2b") "c:/Users/hh/AppData/Local/Temp/yapfPBnoV2")
       nil
       '(""))
```

**Comment by lld2001** [comment]
Thank you for your tip. I finally fixed the error by set `:args` to `nil`. 

```emacs-lisp
(reformatter-define yapf :program "yapf" :args nil)
```

**Comment by purcell** [comment]
`:args` is optional so you can just omit it, I believe.
