### ISSUE TITLE
Idea: pyment

### ISSUE THREAD

**Issue by jgarte** [purcell/emacs-reformatter#45]
https://github.com/dadadel/pyment

Hi,

WDYT of using reformatter with pyment? meh?

**Comment by purcell** [comment]
It's not clear what you're asking with this, sorry.

**Comment by jgarte** [comment]
> It's not clear what you're asking with this, sorry.

I mean to run `pyment` on the current Emacs buffer and convert the docstrings in place.

Pyment is a formatter for Python docstrings.

Might be also nice to have the user select the docstring style that they want to convert to via the `universal-argument` or by some other means...

**Comment by purcell** [comment]
Okay, I mean, you can use reformatter with whatever formatter you want. No changes to reformatter are required for that. There's a `-k` flag for `pyment`, and with `-` as the filename, you should already be able to wrap `pyment` with reformatter.

**Comment by DamienCassou** [comment]
Should this issue be closed?

**Comment by jgarte** [comment]
Yes
