### ISSUE TITLE
Question: how to use ruff for region format

### ISSUE THREAD

**Issue by braineo** [purcell/emacs-reformatter#52]
Hello,

I am trying to integrate region formatting with [ruff](https://docs.astral.sh/ruff/configuration/#full-command-line-interface).

for the full buffer formatting is very straightforward, the problem comes to region format.

it seems reformatter's region format is writing the selected region to a different file, formatting it and taking the content back to the original buffer's region.

ruff (black as well) expects valid syntax for formatting -- cutting a region out ends up to be some invalid syntax to format. ruff  supports `--range` argument for partial format while the whole buffer content needs to send through stdin. 

is there any recommended way to integrate ruff with reformatter?

**Comment by purcell** [comment]
No, there'd be no way to handle that with reformatter currently. But I think the case of selecting and formatting a region that is syntactically invalid is not one that many tools would handle. Cool that ruff tries to do it.

I can imagine how I might add support for this type of behaviour to `reformatter`, but I don't expect it would really be worth the extra complexity.

**Comment by braineo** [comment]
Thanks for the explanation! If that’s not the goal for reformatter I can look for other solutions.
