### ISSUE TITLE
Use the project's root to start the program

### ISSUE THREAD

**Issue by DamienCassou** [purcell/emacs-reformatter#54]
Some tools depend not only on their arguments but also on the directory they are started: e.g., eslint (more precisely some of its 3rd-party rules) usually works better if started from the project's root instead of the buffer's default-directory.

Would you mind a PR adding support for a `:cwd` argument? I envision something like:

```emacs
(reformatter-define eslintd-fix
  :program "eslint"
  :cwd (locate-dominating-file
        default-directory
        (lambda (directory)
          (seq-find
           (lambda (project-marker)
             (file-exists-p (expand-file-name project-marker directory)))
           '("eslint.config.js" "eslint.config.mjs" "eslint.config.cjs" "package.json")))))
```

This would look upward in the filesystem for a directory containing a project marker for eslint. The value of `:cwd` would have to be evaluated dynamically.

**Comment by purcell** [comment]
Yeah, I'd consider something like this. (I might suggest `:working-directory` over `:cwd`.)

**Comment by DamienCassou** [comment]
Thank you for your answer @purcell. What do you about https://github.com/purcell/emacs-reformatter/pull/55?
