### ISSUE TITLE
Failing to use this library for `nix fmt`

### ISSUE THREAD

**Issue by luckysori** [purcell/emacs-reformatter#58]
I love `reformatter.el`, and I was able to use it to create an `-on-save-mode` for `dprint`, but I'm struggling with [`nix fmt`](https://nix.dev/manual/nix/2.18/command-ref/new-cli/nix3-fmt)[^1].

AFAIK, there is no way to tell `nix fmt` to output the reformatted code to stdout, which I think would be the simplest way to work with `reformatter.el`. Given that, I thought it would be possible to do in-place reformatting on a temporary file, but the original file is not getting replaced after the reformatting takes place. Here is the relevant code (I think):

```elisp
(reformatter-define nix-fmt
  :program nix-fmt-command
  :args (list "fmt" input-file)
  :input-file (reformatter-temp-file-in-current-directory)
  :stdout nil
  :lighter " nix-fmt"
  :group 'nix-fmt)
```

And here is the repo for full context: https://github.com/luckysori/nix-fmt.

Another, probably crucial detail: the nix `formatter` I'm using is `treefmt`, via `treefmt-nix`.

[^1]: Not to be confused with `nixfmt`!

**Comment by luckysori** [comment]
I was indeed failing to use this library.

I fixed my problem by accepting that `nix fmt` does not offer the necessary APIs to work with `reformatter.el`, and realising that I needed to work with the underlying `treefmt` instead.

The correct reformatter definition is:

```elisp
(reformatter-define nix-fmt
  :program nix-fmt-command
  :args (list "fmt" "--" "--stdin" input-file)
  :input-file (reformatter-temp-file-in-current-directory)
  :lighter " nix-fmt"
  :group 'nix-fmt)
```

**Comment by bestlem** [comment]
However the program  nixfmt which its what nix fit calls does provide the correct API so if you use that executable rather than the nix command it will work with reformatter.el

**Comment by purcell** [comment]
I published a package for `nixfmt` recently btw: https://github.com/purcell/emacs-nixfmt

**Comment by purcell** [comment]
Not quite the same as `nix fmt`, of course, but it sounds like they'll be converging?
